stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk update && apk add openssh-client
    - chmod 400 ${SSH_PRIV_KEY}
  script:
    - ssh -o StrictHostKeyChecking=no -i ${SSH_PRIV_KEY} agnes@34.133.211.90"
      sudo bash testing.sh"
    - ssh -o StrictHostKeyChecking=no -i ${SSH_PRIV_KEY} agnes@34.68.143.87"
      sudo bash testing.sh"
  